name: Deploy to EC2

on:
  push:
    branches:
      - main   # Jab main branch pe push hoga to deploy hoga

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2


      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 16.171.193.154
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls




      # - name: Deploy to my EC2 instance
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     SOURCE: .
      #     REMOTE_HOST: ${{ secrets.HOST_DNS }}
      #     REMOTE_USER: ${{ secrets.USERNAME }}
      #     TARGET: ${{ secrets.TARGET_DIR }}

      # - name: Executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_DNS }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd ${{ secrets.TARGET_DIR }}
      #       npm install --production
      #       pm2 restart all || pm2 start app.js
